project:
  title: "scripts"
  type: default
  output-dir: "output"
  execute-dir: file
  render:
    - Import_Data.qmd
    - Descriptive_Analyses.qmd
    - RQ1_Analyses.qmd
    - RQ2_RQ3_SR_Models.qmd
    - RQ4_Analyses.qmd
    - Production_Run.qmd

